### ISSUE TITLE
need something to work out how to follow the lines

### ISSUE THREAD

**Issue by smeagolthellama** [smeagolthellama/drawing-robot#2]
I have what is needed to make the images, and I am working on the hardware end (I guess that this would be the "front" end :smiley: ), but this would need some sort of input coordinates. Could @jozsefsallai work on a system to turn a black&white png (or ppm if you prefer) image (white lines need following) output by an edge-detection algorithm into a route (preferred format would be something like an arbitrary number of lines, each containing "$x $y" pairs (pixel coloumn and row(I'll take care of the coordinate transformation)))? A simulation of a line-following robot might do the trick. :smile:

**Comment by jozsefsallai** [comment]
Wouldn't it be better if we decided on a single format instead of having .png *or* .ppm? (I think PNG would be a better option here)

**Comment by jozsefsallai** [comment]
Added coordinates generator application source code to the repo. Please refer to the comment in the commit to build from source.

**Comment by jozsefsallai** [comment]
Added a `go run` command to `makeNew.sh`. If this output is ok with you then I will close the issue.

**Comment by smeagolthellama** [comment]
By png/ppm I meant that the choice is yours.
Also, the order would be better as a route for a "pencil" to follow. Another thing, what are the dependencies of go (as in apt)?

**Comment by smeagolthellama** [comment]
Ah. forget about the dependency problem, didn't see the readme modifications.

**Comment by smeagolthellama** [comment]
Just ran it, and "output .txt" is not the best of names. If you could change it to be something like $name.coords.txt, that would be better.

**Comment by jozsefsallai** [comment]
> Also, the order would be better as a route for a "pencil" to follow

I'll think about this.

> Just ran it, and "output .txt" is not the best of names. If you could change it to be something like $name.coords.txt, that would be better.

Sure!

**Comment by jozsefsallai** [comment]
`$name.coords.txt` naming done in 68d653bd7d19f7ad974fac46071fa94a788d8dc3

**Comment by smeagolthellama** [comment]
right. any way of either from the makefile, or the go... thing... (is it a program or a script?) find out what the shell script just made? I have separated the calling of the coordinator and the imaginator (:grin:), but have no Idea on how to get the right parameter for the former.

**Comment by smeagolthellama** [comment]
abc57337909a56e81de069020f57f9ea4e76fd7f has the last sort-of resolved. (very dirty hack.)

**Comment by jozsefsallai** [comment]
> is it a program or a script?

with `go run`, it's a script, when compiled, it becomes an executable program

>very dirty hack

made it less dirty and more precise in ed590675bcd8afa32cb2cdf32bbfcbdf48185653

**Comment by jozsefsallai** [comment]
I stopped following this when Perl started to get involved. No offense, but Perl needs to die already.
